### PR TITLE
merging some modified features and API preparation to dev branch

### PR DESCRIPTION
**Pull request by CirrusPreeminent**
Merge:
- ProductDetail
- MyPurchase

create some API usage functionality on both pages
and adjust ProductDetail content layout to look more clean

### CODE REVIEW

**Review by TeeThanakit — APPROVED** [review]
Great job!!

**Review by mojisungg — COMMENTED** [review]
You’ve got it.

**Review by aritatgml — APPROVED** [review]
lgtm

**Review by YuilTripathee — APPROVED** [review]
Looks good to me

**Pull request merged**
